#  To run in the foreground
#  > docker-compose up
#
#  To run in the background and tail the logs
#  > docker-compose up -d
#  > docker-compose logs -f
#
#  Subsequent builds for any changes in dockerfile.
#  > docker-compose build

version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: docker
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      APP_PORT: 80
    ports:
      - 80:80
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: docker
    ports:
      - 5432:5432
